apiVersion: v2
name: cheqd
description: A Helm chart to deploy Cheqd localnet node in Kubernetes
type: application
version: 0.1.0
appVersion: 4.1.1

# dependencies:
#   - name: common
#     version: 2.x.x
#     repository: oci://ghcr.io/didx-xyz/bitnami-oss-charts
