fullnameOverride: driver-did-cheqd

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

image:
  registry: ghcr.io
  name: cheqd/did-registrar
  pullPolicy: Always
  tag: develop
  digest: sha256:52221271f250ef162a1b83576fc0dff63e96d1d7897e8d0106eebec925f0519f

service:
  appProtocol: http
  port: 3000
  containerPort: 3000

livenessProbe:
  tcpSocket:
    port: 3000
readinessProbe:
  tcpSocket:
    port: 3000
startupProbe:
  tcpSocket:
    port: 3000

secretData:
  # FEE_PAYER_TESTNET_MNEMONIC: "" # Cheqd did-registrar uses testnet faucet by default
  # FEE_PAYER_MAINNET_MNEMONIC: "..."
  # Use the same Testnet Mnemonic as the Localnet Cheqd node
  FEE_PAYER_TESTNET_MNEMONIC: betray purity grief spatial rude select loud reason wolf harvest session awesome

env:
  # TESTNET_RPC_URL: https://rpc.cheqd.network
  # MAINNET_RPC_URL: https://rpc.cheqd.net
  TESTNET_RPC_URL: http://cheqd:26657
  # RESOLVER_URL: https://resolver.cheqd.net
  RESOLVER_URL: http://did-resolver:8080

podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 1000
