fullnameOverride: tails-server

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  ad.datadoghq.com/tails-server.logs: >-
    [{
      "source": "python.uvicorn",
      "service": "tails-server",
      "log_processing_rules": [{
        "type": "exclude_at_match",
        "name": "exclude_health_probes",
        "pattern": "GET /health/(ready|live) HTTP/\\d\\.\\d\"\\s+200\\s+OK"
      }]
    }]
  proxy.istio.io/config: >-
    proxyMetadata:
      ISTIO_META_IDLE_TIMEOUT: 0s
    terminationDrainDuration: 35s
podLabels:
  admission.datadoghq.com/enabled: "true"

image:
  name: acapy-cloud/tails-server
  pullPolicy: Always
  tag: master

ingressDomain: acapy-cloud.dev.didxtech.com
ingress:
  internal:
    enabled: true
    className: nginx-internal
    rules:
      - host: tails-server-{{ .Values.ingressDomain }}
command:
  - poetry
  - run
  - uvicorn
  - tails.main:app
  - --log-config=/tmp/log_conf.yaml
  - --reload
  - --host
  - 0.0.0.0
  - --port
  - 6543

secretData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: password
env:
  S3_BUCKET_NAME: acapy-cloud-public
  S3_ENDPOINT_URL: http://minio:9000

service:
  port: 6543
  containerPort: 6543
  appProtocol: tcp

livenessProbe:
  httpGet:
    port: 6543
    path: /health/live
readinessProbe:
  httpGet:
    port: 6543
    path: /health/ready
  initialDelaySeconds: 5

persistence:
  enabled: false

extraVolumes:
  - name: tmp-tails
    emptyDir: {}
extraVolumeMounts:
  - name: tmp-tails
    mountPath: /tmp/tails

podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsUser: 65534

# resources:
#   requests:
#     cpu: 50m
#     memory: 128Mi
#   limits:
#     cpu: 250m
#     memory: 256Mi

configFiles:
  log_conf.yaml:
    path: /tmp/log_conf.yaml
    content: |-
      version: 1
      disable_existing_loggers: False
      formatters:
        default:
          "()": uvicorn.logging.DefaultFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(message)s'
          use_colors: null
        access:
          "()": uvicorn.logging.AccessFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(client_addr)s - "%(request_line)s" %(status_code)s'
      handlers:
        default:
          formatter: default
          class: logging.StreamHandler
          stream: ext://sys.stderr
        access:
          formatter: access
          class: logging.StreamHandler
          stream: ext://sys.stdout
      loggers:
        uvicorn:
          level: INFO
          handlers:
            - default
          propagate: no
        uvicorn.error:
          level: INFO
        uvicorn.access:
          level: INFO
          handlers:
            - access
          propagate: no
