fullnameOverride: did-registrar

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

image:
  registry: docker.io
  name: universalregistrar/uni-registrar-web
  pullPolicy: Always
  tag: latest
  ## Multi-Arch Digest
  digest: sha256:f94053ab9b7ee8104f88bc9ecceeb0353455a9559ec1ab933f9fab7588d67f16
  ## If things start breaking, this is a known good SHA but isn't Multi-Arch
  # digest: sha256:d02207a156cb97dd79d3515bc90a963d12660c4ca82382f77ae6b5d32351267f

env:
  # Disable the Spring Boot banner
  SPRING_MAIN_BANNER-MODE: off
  ## Be very careful, this can do _a lot_ of logging
  ## Valid levels are: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  LOGGING_LEVEL_ROOT: WARN
  LOGGING_LEVEL_uniregistrar: WARN

service:
  appProtocol: http
  port: 9080
  containerPort: 9080

livenessProbe:
  tcpSocket:
    port: 9080
readinessProbe:
  tcpSocket:
    port: 9080
startupProbe:
  tcpSocket:
    port: 9080

env:
  LOG_LEVEL: "warn"
